allowBuilds:
  '@parcel/watcher': true
  '@prisma/engines': true
  core-js: true
  noblox.js: true
  prisma: true
  protobufjs: true
  sharp: true
  unrs-resolver: true
onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@prisma/client'
  - '@prisma/engines'
  - core-js
  - noblox.js
  - prisma
  - sharp
  - unrs-resolver
